### ISSUE TITLE
Request: WinKey as modifier

### ISSUE THREAD

**Issue by stavfx** [Belphemur/SoundSwitch#109]
Thanks for making exactly the utility I was looking for!

I only wish that the WinKey will be treated as a modifier key, so I could bind something like "Win+A" or "Win+Shift+A".

Thanks again!

**Comment by Belphemur** [comment]
Should be easily doable, I'll give it a lot asap.

**Comment by Belphemur** [comment]
In fact it wasn't easy.

C# is doing it's best to be sure the developer won't use the WinKey ... Anyway, it's done and working.
If you could also test it, that'd be great.

**Comment by Technetium1** [comment]
@Belphemur Works perfectly for me on Windows 10 x64.

**Comment by stavfx** [comment]
It works on Win 7 x64!
However there's a small visual issue, as you'll see in the attached photos. It behaves a little differently than the other modifier keys.
![ssalt](https://cloud.githubusercontent.com/assets/1842250/17847983/a8bb60a0-6859-11e6-8b22-2a9175f008f6.jpg)
![sswin](https://cloud.githubusercontent.com/assets/1842250/17847984/a8c14ac4-6859-11e6-8823-22c6f401055f.jpg)

Like I said, This is a visual issue only, and the key binding works perfectly as expected (so I'm happy with the current state).

Thanks!!

**Comment by Belphemur** [comment]
Yeah I'm aware of the little glitch.

It's because C# doesn't recognize the windows key as a modifier (like ctrl, alt or shift), I had to interface directly with one of the windows library to catch the Win key and other key pressed in the same time.

For C#, in this case, the Win key is not pressed, only the A key. I'll see later if I can do something about the key appearing like this.

**Comment by Technetium1** [comment]
This doesn't happen on Windows 10.
![settings](https://cloud.githubusercontent.com/assets/9877150/17858607/5812b8b0-6854-11e6-9b82-4031ea787ab7.png)
