### ISSUE TITLE
PageTable leak？

### ISSUE THREAD

**Issue by Tback1** [Belphemur/SoundSwitch#1115]
### What happened?

Why need so much pageTable VM？？ Even >500 MB

![2023-02-101429](https://user-images.githubusercontent.com/8872546/218024620-a9f990e4-b92f-4ec2-9a4e-04b50a78cbcd.jpg)

### Step to reproduce

normal run the soundswitch

### Version

6.5.x

### What version of Windows are you seeing the problem on?

Windows 7

**Comment by Belphemur** [comment]
How long are you running SoundSwitch ?

Could you attach the content of %appdata%/SoundSwitch ?

On my side I rarely get SoundSwitch taking more than 50 Mb of memory:
![Screenshot 2023-02-10 071758](https://user-images.githubusercontent.com/197810/218090766-a9aaa08a-8784-4ec0-9aef-1edfe61b1e5f.png)

**Comment by Tback1** [comment]
@Belphemur 
this is the content of %appdata%/SoundSwitch
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/10716309/SoundSwitch.zip)

I just see the memory use at the soundswitch start. 
the machine have 32GB memory ,so I turn off the pagefile on it ,so could't have so much VM memory  to use.

**Comment by infomaniac50** [comment]
> The machine have 32GB memory ,so I turn off the pagefile on it ,so could't have so much VM memory to use.

This might be from the memory subsystem in use by the process. A lot of page table allocations are virtual and don't exist until data is written to them. This is especially so on an idle machine. By turning off the pagefile you are forcing Windows to use real memory allocations in RAM instead of a sparse allocation on disk.

You can crash the system by running out of virtual memory even if physical usage is less than 50%. Turn the pagefile back on but don't use automatic management. Instead set a custom size with the minimum and maximum page file size to 16384 MB. This allows Windows to use sparse virtual memory while also setting hard limits on any runaway processes.
