### ISSUE TITLE
Tray icon (and tooltip) changes after connecting device

### ISSUE THREAD

**Issue by jdvegmond** [Belphemur/SoundSwitch#1134]
### What happened?

Whenever I connect a (sound) device to my laptop, the tray icon changes to 'headset' even if I don't change the playback device at all (pc speakers still the active device).

### Step to reproduce

- Started laptop, with PC Speaker and Jabra headphone connected. Both are configured to be able to switch to with the tool. PC Speaker is the active device and icon in system tray is a speaker.
- Connected a JBL speaker just to charge it but it was still recognized by Windows as new device. The device is not selected as one to change to with the tool.
- Tray icon, and its tooltip show that the headphone is now active, but when clicking the icon, the speaker is still active. And when playing music, the speaker is indeed still the active device.

![image](https://user-images.githubusercontent.com/32638636/221794968-be6720f0-0fa3-40de-a27e-fe3126c12b16.png)

![image](https://user-images.githubusercontent.com/32638636/221795056-996275be-bdf6-4376-b70b-15b3e1ed7136.png)

(I never change the setting for the microphone, it's always on the headphone when it is connected.)

### Version

v6.5.4.0

### What version of Windows are you seeing the problem on?

Windows 11

**Comment by Belphemur** [comment]
Hello,

If Windows change the default device, you'll see a notification and the icon will change.
This happens when the device connect was a previous default device, windows change automatically to it.

In this case, the Jabra was set back as the default communication device when it has been connected.
I can change the behavior to avoid changing the icon when it's the communication device.

**Comment by Belphemur** [comment]
Will be available for testing with the nightly: https://soundswitch.aaflalo.me/nightly
