### ISSUE TITLE
Windows anerversary bug

### ISSUE THREAD

**Issue by budtz** [Belphemur/SoundSwitch#119]
Every time exit a game or something running fuld screen the program pops up and says it has switched audio device and makes the sound. Has been this way since windows anneeversery update. This is mostly with a tv conected to the pc and running two monitors

**Comment by Belphemur** [comment]
Hello @budtz,

This isn't caused by Windows 10 or the anniversary update, it's more likely that SoundSwitch detects that an exterior source changes the default audio device. This is the normal behaviour since SoundSwitch uses the Windows API to get notified when such event happens.

You disable the notification if it's bothering you.
