### ISSUE TITLE
Windows XP compatible version

### ISSUE THREAD

**Issue by LeBaux** [Belphemur/SoundSwitch#133]
Hi, latest version is not compatible with winXP - that I understand, but I know there was a version working on XP. Could you please include download link to this legacy version somewhere on your website, please? Thanks!

**Comment by Belphemur** [comment]
Hello @LeBaux,

I'm not aware of any version of SoundSwitch working with Windows XP.

The library/API used to switch the default device is working only with Vista and later versions of Windows.

Since I took up the development, I never released a version for Windows XP since it was already at the end its life. I'm sorry, but I can't help you with this request.

**Comment by LeBaux** [comment]
Hi, thanks for the reply, I wound never ask you to make it work under XP, I was just under false impression that there is indeed XP version... my mistake, sorry!
