### ISSUE TITLE
Crash on Launch, Win7 x64

### ISSUE THREAD

**Issue by ReanimationXP** [Belphemur/SoundSwitch#161]
References Notification creation I think.  This happens with damn near every version, even ones which have worked. I suspect a restart would fix, but keeps happening.

Also Github wouldn't let me upload the zip you're generating. Even after trying a handful of evasion bullshit. Uploaded it here:

https://mega.nz/#!sNQjHbhS!5UIV1uG2dDuuD7CwB5NSIvYgtSyMd0wrZ0K9Vy0wnn4

**Comment by FireEmerald** [comment]
Do you remember which kind of **Notification** (None,Windows,Sound,Toast,Custom) you had configured to show up if you changed your devices?

The error occurred because you are using Windows 7 and configured:
`"NotificationSettings": 3` - which is Toast and Toast isn't available under Windows 7.

The easiest way to fix your problem is to delete the configuration file:
`%AppData%\Roaming\SoundSwitch\SoundSwitchConfiguration.json`

Nevertheless @Belphemur there could be a small issue introduced in 0bc54a473feeeec5e2817b2d77a4a91ccee7b3b5.
I changed the order of the Notification Sound labels and the Device Cycler labels to be more sorted.

https://github.com/Belphemur/SoundSwitch/commit/0bc54a473feeeec5e2817b2d77a4a91ccee7b3b5#diff-0e21116805b3be8f8d8dbbae3b79682eR27
https://github.com/Belphemur/SoundSwitch/commit/0bc54a473feeeec5e2817b2d77a4a91ccee7b3b5#diff-2b6dc1a219c42e63a3595fdb591f4b05R24

**Comment by Belphemur** [comment]
@fireemerald it surely that yes. 

We need to either put them in the order they were or add a backward compatible setting in the configuration. 

The easiest is to rechange the order in the enum

**Comment by Belphemur** [comment]
@ReanimationXP is I'm sorry but for now you'll have to remove the %appdata%/SoundSwitch directory to start with a fresh configuration.

**Comment by FireEmerald** [comment]
Well, but `"NotificationSettings": 3` wasn't changed - so the source of this crash shouldn't be the localization commit.

**Comment by Belphemur** [comment]
In that case I'll add a fallback for the notification setting. Since each notification has an IsAvailable method. 

This way we'll avoid this type of crash. 

It would be nice to know how this setting has been set in the first time. 

⁣Sent from BlueMail ​

**Comment by FireEmerald** [comment]
It would be good to assign each Enum a value which is used in the configuration.

**Comment by FireEmerald** [comment]
I deleted a comment from me. The only file changes which lead to this crash aren't found inside the **NotificationFactory.cs**, instead the it was: **[NotificationTypeEnum.cs](https://github.com/Belphemur/SoundSwitch/commit/0bc54a473feeeec5e2817b2d77a4a91ccee7b3b5#diff-e5c0d47cc4eb7013b7b5cb73a9c1f456R18)** ...
