### ISSUE TITLE
Change speaker layout between Stereo and 5.1

### ISSUE THREAD

**Issue by kathampy** [Belphemur/SoundSwitch#212]
Can you add support for changing the current speaker layout, say from Stereo to 5.1, with a hotkey and from the tray menu?

**Comment by Belphemur** [comment]
Hello @kathampy 

As much as this would be an interesting feature, the windows code that set this part hasn't been reverse engineered for me to use.

Unfortunately, I don't have knowledge in reverse engineering, this won't be possible without somebody that can do that with Windows's code.

**Comment by kathampy** [comment]
Thanks anyway. I found another another project also called soundswitch that does it with an AutoIt script.

**Comment by Zentriert** [comment]
The ability to change from stereo to 5.1 using hotkeys was in the original versions of this app, including version 2 and 3. I know this is a fork, but why was it removed? 

I see @kathampy mentioning finding the older version, I've been lead to assume these are both based on the same code due to this page: https://archive.codeplex.com/?p=soundswitch

I appreciate the new GUI, but I see no ini to configure and no way to change my number of audio channels, so sadly I cannot use your version and must continue using the older, depreciated one. 

I see you've said the feature in Windows has yet to be reverse engineered, I don't think it ever was; the older versions simply using a shortcut to open the Windows Sound options page and then uses some kind of script to change the audio output, similar to AutoHotKey. Like a macro. 

Like when you use it to change the number of audio channels, you can see the Windows Sound dialog open momentarily and close. 

So why can't it just be kept the way it was before? I'm not really understanding what has to be reversed engineered. 

Thanks for keeping the project alive!

**Comment by kathampy** [comment]
@Zentriert This is the app I'm currently using: https://github.com/dmwyatt/soundswitch

**Comment by Belphemur** [comment]
@Zentriert This never been a feature of SoundSwitch.

I think you're mixing with the project linked by @kathampy 

I'm against doing any code that open program and interact with them as the user. Since I wouldn't want a program doing that on my machine.
