### ISSUE TITLE
Change banner position?

### ISSUE THREAD

**Issue by mikolajek** [Belphemur/SoundSwitch#242]
Is there any way to change the banner's default position?
With my 4K display I'd love to have next to the tray rather than in the left upper corner.

**Comment by debido666** [comment]
Yes, it would be nice to change position of Banner. 
Say, five points of a screen? 
Upper left, right, center. Lower left, right?

**Comment by fishbiscuit13** [comment]
Is there any chance this could be worked on? Surprised it hasn't been implemented after being suggested over two years ago.

**Comment by Belphemur** [comment]
Because it's a lot of trouble to implement especially when people have multiple screens.

I've simply decided it's not worth my time for now to implement it and to deal with the issue that will be related to different people setup + the time to design and implement its UI.

And the following request of "I don't like the choices, I want to have it here, etc ...".
For now, it's on the top left.
