### ISSUE TITLE
Crash on boot after motherboard change

### ISSUE THREAD

**Issue by barnstorm3r** [Belphemur/SoundSwitch#251]
I recently downsized my PC, which involved changing from an ASUS Prime X370-Pro to an ITX ASUS board (B350-I Gaming). Now, SoundSwitch crashes every time I boot. I'm running Windows 10 Pro x64 1709 with all the latest quality updates as of April 1st (KB4088776). I'm using SoundSwitch to change between a set of 3.5mm speakers attached to my motherboard headers and my USB headset. AppData folder and crash logs attached. I should mention that, after launching the application manually through the Start Menu, it works perfectly.
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/1866344/SoundSwitch.zip)
[SoundSwitch-crashlog-1_4_2018.zip](https://github.com/Belphemur/SoundSwitch/files/1866345/SoundSwitch-crashlog-1_4_2018.zip)
[SoundSwitch-crashlog-30_3_2018.zip](https://github.com/Belphemur/SoundSwitch/files/1866346/SoundSwitch-crashlog-30_3_2018.zip)

**Comment by FireEmerald** [comment]
I would suggest to uninstall SoundSwitch and make sure `%AppData%\SoundSwitch` is also deleted. Then reinstall SoundSwitch and tell us if the problem persists. Seems like something went wrong while unregister hotkeys.

**Comment by barnstorm3r** [comment]
Alright, I'll have a look. Thanks!

**Comment by barnstorm3r** [comment]
Just rebooted having reinstalled, to be greeted with a crash again. Here's the log:
[SoundSwitch-crashlog-15_4_2018.zip](https://github.com/Belphemur/SoundSwitch/files/1913366/SoundSwitch-crashlog-15_4_2018.zip)

**Comment by FireEmerald** [comment]
Please update to the latest version - if the problem persists, you can use the following workaround, because you said:

>  I should mention that, after launching the application manually through the Start Menu, it works perfectly.

1. Create a new text file called `startSoundSwitch.bat` somewhere. (`.bat`, not `.txt` !)
2. The content of the file should be: `start /d "C:\Program Files\SoundSwitch" SoundSwitch.exe`
3. (optional) The path must be changed if you installed SoundSwitch somewhere else.
4. Close SoundSwitch, double click onto the file, SoundSwitch must start.
5. Press `[WIN]` + `[R]`, enter `shell:startup` and press OK.
6. A directory will be opened, create a shortcut of your `startSoundSwitch.bat` file and move it to this directory.
5. Edit the properties of your shortcut and set **Run: Minimized**.
6. You're done. When your computer starts, SoundSwitch will start.
