### ISSUE TITLE
How to test my forked Soundswitch-dev installer?

### ISSUE THREAD

**Issue by aleczk** [Belphemur/SoundSwitch#273]
Olá,

I'm not used to program at all, but I'm trying to make you have the option to install the program directly in Portuguese (Brazil). I noticed (and I might be wrong) by looking at other threads that you should change the **setup.iss, products.iss** and **README.me** (this last seems optional) and I did the changes and added some lines; But I'm suspicious that it's too easy to be true.
 
I'd like to know who can I test it before I submit a pull change. **How can I run the installer in this SoundSwitch-dev folder that I forked and made changes?**

I looked up in the web but I found a lot of things but none seems to describe what I want to do. I tried GitBash and GitHub Desktop but tbh I had little idea of what I was doing.

Obrigado! (Thank You)

EDIT: Just in case, I'm pasting here the 3 files I mentioned before in a .zip
They belong, respectively, to
_1. SoundSwitch-dev\
2. SoundSwitch-dev\Installer\scripts
3. SoundSwitch-dev\Installer_

[InstallerPTBR.zip](https://github.com/Belphemur/SoundSwitch/files/2004331/InstallerPTBR.zip)

**Comment by FireEmerald** [comment]
> How can I run the installer in this SoundSwitch-dev folder that I forked and made changes?

You need to compile the [Installer/setup.iss](https://github.com/Belphemur/SoundSwitch/blob/dev/Installer/setup.iss) file using Inno Setup.

`setup.iss` -- compile --> `Final\SoundSwitch_v_Installer.exe` --> Test the installer.

1. Download Inno Setup from [here](http://www.jrsoftware.org/download.php/ispack-unicode.exe) and install it.
2. Download the source code of SoundSwitch, if not already done [here](https://github.com/Belphemur/SoundSwitch/archive/dev.zip).
3. Unpack the downloaded `SoundSwitch-dev.zip`
4. Replace the Installer/`setup.iss` with [this one](https://gist.github.com/FireEmerald/84581291e8066065f79697f8c1ddc994).
5. It's a "stub setup file" which means you can compile it, get a installer, which doesn't install anything on your system, expect the uninstaller inside the installation directory.
6. Start the Inno Script Studio and open the `setup.iss` file:
![2018-05-15 19_43_43-window](https://user-images.githubusercontent.com/1107939/40074175-3657ea6c-5879-11e8-9e73-9ea8d40dba98.png)
7. 1>2>3>4 and press **(5)** to compile the `setup.iss`. After compilation your installer is located in `Final\SoundSwitch_v_Installer.exe`.
8. Run the installer and check if your strings are correct.
9. Run the uninstaller to "uninstall" your testing installation of SoundSwitch located in the installation directory.

Now add your language after this line:
https://github.com/Belphemur/SoundSwitch/blob/886a434f7ea67bea89c864559ea151c8033665be/Installer/setup.iss#L61 Just use the `Default.isl` file.

and Translate:
https://github.com/Belphemur/SoundSwitch/blob/886a434f7ea67bea89c864559ea151c8033665be/Installer/setup.iss#L116-L141
https://github.com/Belphemur/SoundSwitch/blob/886a434f7ea67bea89c864559ea151c8033665be/Installer/scripts/products.iss#L10-L56

Re-run **(5)** from the screenshot and your new installer should be compiled.

**Remarks:**
You won't be able to test all strings due to the fact that the installer e.g. doesn't download anything while the installation process which it normally perhaps does. To get this to work you must uncomment some of the code inside the `setup.iss`.

**Comment by FireEmerald** [comment]
@Belphemur How about adding the strings from the installer weblate so they can be translated?

**Comment by aleczk** [comment]
I'm having a little problem when I try to edit with the Inno Script Studio, the foreign characters seems all messy. What should I do? Thanks. @FireEmerald

**Comment by FireEmerald** [comment]
See 8c9b63bdebab400c4bf846f763e93afd2998e3c4 for the enconding problem. I also edited these files always with Notepad++.
