### ISSUE TITLE
Incorrect tray icon displayed

### ISSUE THREAD

**Issue by zeeh1975** [Belphemur/SoundSwitch#340]
Since (I think) version 4.13 (4.14 has the same problem) after a while of having the program running it stop showing the correct device icon, it's start showing a mic icon, whe I switch device it's shows the correct icon for a while (200ms or so) and then shows that mic icon. Obviously closing and starting the app again fixes the problem for a while.
Mic icon:
[Mic](https://i.imgur.com/T8p18hB.png)

Correct icons
[Headphones](https://i.imgur.com/H0sGQCl.png)
[Speakers](https://i.imgur.com/zVjvUoi.png)

OS: Windows 10 ver 1809 (17763.475) 64 bits

**Comment by Belphemur** [comment]
I see the issue.

The icon change when the device change, when you plug your headset, Windows detect first the new headphone then the microphone.

Triggering 2 notifications:

1.  Headphone -> Icon change to Headphone
1. Microphone -> Icon change to Microphone and stays there since it's the last change.

I shouldn't change the icon when the microphone device changes.

**Comment by zeeh1975** [comment]
To clarify, both devices (Internal Realtek audio and Logitech G633 headphones) are always plugged in, I just switch between them while game/stop gaming. 
Also I don't have any recording device selected in SoundSwitch setup.

[Options page 1](https://i.imgur.com/svVxeAx.png)
[Options page 2](https://i.imgur.com/qsPLZLv.png)
[Options page 3](https://i.imgur.com/FwgwRs9.png)
