### ISSUE TITLE
Default audio is switching but my opened programs do not.

### ISSUE THREAD

**Issue by jamalrashed** [Belphemur/SoundSwitch#343]
Hey guys, I've been using sound switch for a while and about a month or two ago when updating windows it stopped working properly. When i hit my hotkey it will switch the default audio device but some programs that are currently running will continue to run in my other device. For example, when playing certain games with my headphones set as default when i switch to my monitor speakers the games audio will stay playing through my headphones unless I open my sound control panel and disable my headphones. I found this issue posted and closed but it was posted a few years ago and didnt seem to be solved. Heres a link https://github.com/Belphemur/SoundSwitch/issues/42

**Comment by FireEmerald** [comment]
Instead of switching the playback device using SoundSwitch, could you test if the problem doesn't occur if you use the windows menu instead? If that doesn't work either, it's not a fault of SoundSwitch.

![2019-06-13 09_41_58-](https://user-images.githubusercontent.com/1107939/59415356-99346e00-8dc3-11e9-99d2-22f68cc4f904.png)
![2019-06-13 09_42_58-Window](https://user-images.githubusercontent.com/1107939/59415359-9afe3180-8dc3-11e9-9f7d-3ee2d0c6cbe1.png)

**Comment by jamalrashed** [comment]
Thanks for replying! I tested this and the problem still persists, some audio wont go through the monitor speakers unless i disable my headphones, and vice versa. Would you happen to know a solution to this?

**Comment by FireEmerald** [comment]
As it is written in the wiki your issue could be caused by nearly anything expect SoundSwitch. The application itself, your drivers or a 3rd party application. I'm really sorry but you have to check that on your own by try-and-error.
