### ISSUE TITLE
Install / Upgrade issue

### ISSUE THREAD

**Issue by stephen147** [Belphemur/SoundSwitch#404]
Here's my issue that pops up when I go to install or upgrade the version.

This issue goes away when I run the installer as an admin (which I don't like doing)

![image](https://user-images.githubusercontent.com/14054664/73956990-9f043400-48fd-11ea-8a7f-5f23dabd0957.png)

Also here my zipped folder: `%AppData%\SoundSwitch`

[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/4166332/SoundSwitch.zip)

**Comment by Belphemur** [comment]
Hello, 

If you want to install it as user, you should uninstall it and then reinstall it as user in your own home directory. 


Sent from Nine
________________________________

**Comment by stephen147** [comment]
Hi,

I got this error when I tried it on a fresh install also and I choose only install for me (Single user).

Here's the installer I'm using: **SoundSwitch_v5.0.1.14646_Release_Installer.exe**

My OS details are: `Version: 1909`

![image](https://user-images.githubusercontent.com/14054664/73966161-6704ed00-490d-11ea-826c-8827605a7152.png)

**Comment by Belphemur** [comment]
Hoo that's a bug. 

For now, just don't select creating a shortcut for SoundSwitch. 

I'll have to fix the installer. 

Sent from Nine
________________________________

**Comment by Belphemur** [comment]
Will be fixed in a next release.
Thanks again for the bug report !

**Comment by snakecase** [comment]
It seems this problem still exists (just updated :P) for autoupdating C;\ProgramFiles installations which brings a question to my mind: what's the problem with setting `requestedExecutionLevel` to `requireAdministrator` in the app's manifest or at least replacing `Skip this file (not recommended)` button in OP (since it's not an option in a real world) button with `Run as Administrator` which just re-executes the downloaded installer? Or even better, make a check for permissions to the app's installed location **before** executing the downloaded installer and bring a dialog to run as Administrator if it is required. Those users who want to install the app into elevated locations will have no problem granting them to the installer and those who don't want to compromise their security will seamlessly install it into their user's folder as usual.

It will also be cool to add the same permissions check to the installer itself for first-time installations so new users won't have to cease the whole process after encountering the error in OP just to run the installer as Administrator from context menu again.

**Comment by Belphemur** [comment]
@snakecase Created an issue for it.

I should be able to make the updater detect how is soundswitch installed and run the installer in the right mode.
