### ISSUE TITLE
Default Audio device switching - programs are not

### ISSUE THREAD

**Issue by Reversals123** [Belphemur/SoundSwitch#42]
Hi guys. i've been using this for a few months, and recently reccomended it to a friend. he noticed that when he uses it, if he presses his hotkey it will switch the audio device, but any audio that was currently playing will continue to output to it's original source, rather than switching as well.

for me, it switches all audio to output to any given device (which was my desire)

I just reinstalled windows last night and now it seems to behave like his system now, and id prefer it to just force-switch any running programs over to the next audio device. any ideas why it's doing this and how to handle it?

Windows 10 64Bit for me, Windows 7 64Bit for him.

**Comment by Belphemur** [comment]
Hello,

Can you tell me your version of Windows ? (pro/home and build number 
(win + x -> cmd as admin -> type 'winver' without the quote)
I'm pretty sure you have Windows 10 Pro edition.

Can you check if SoundSwitch is selecting the wanted device (click on 
the try icon with the left clic and see if the right sound card has the 
checked icon).

**Comment by Reversals123** [comment]
I'm using Windows 10 pro. i opened playback devices and when i switch outputs with my hotkey, or the tray icon, i can watch it change the default device when i ask it to. i also hear windows 10's notification sound switch between sound outputs as well, it just doesnt pick up the audio from some programs that were open prior to switching.

so far, iTunes and Chrome both stay fixed at their original output

and Media Player Classic will switch on demand, as expected

thanks for your help

**Comment by Belphemur** [comment]
It's an issue with the OS and the different program.
If you try the last beta version of Chrome you'll see it doesn't happen.

I can't really help for that. All I can advise you is to keep updated 
all your programs and OS since it's clearly coming from there. I think 
the last update (1511) for Windows 10 Pro have changed some of the 
things in the API to output sound. The different programs need to update 
their use of the API.

You can see in other closed issue the problem was reported for chrome :)

**Comment by Reversals123** [comment]
ok fair enough, thanks. and yeah I wasn't previously on 1511 until my reformat of my OS so that's probably true. thanks for the answers
