### ISSUE TITLE
Setting audio levels of currently active device

### ISSUE THREAD

**Issue by Varen** [Belphemur/SoundSwitch#452]
**Is your feature request related to a problem? Please describe.**
Often changing the audio of one program means that everything else is skewed proportionally, and it takes a while to go through every other program in the audio mixer and setting it to the same level.

![image](https://user-images.githubusercontent.com/3650235/82511309-3f790f80-9b0d-11ea-88f9-4c667cc07ad5.png)

**Describe the solution you'd like**
An input that allows to set all active programs on that device's audio to the same level as the device itself. For example, if the device is set at 30%, every program would be set to 30%.

**Comment by MrFriendism** [comment]
Oh, I was wondering the same few days back. It becomes really troublesome sometimes to go through every program and even try to level them up at the same point.

That will be another problem solver part of SoundSwitch if we get this.

**Comment by FireEmerald** [comment]
I don't see a good use case for such a feature. I also lower some applications as shown in the screenshot above. But once configured i do not move them. They move if the master volume is modified. If you want to set everything back to 100%, stop playing music, move every slider to 100% and you are done.

**Comment by Bip901** [comment]
I had exactly the same problem.
Try using EarTrumpet instead of the default audio mixer ([Website link](https://eartrumpet.app/)) ([Microsoft Store link](https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)) ([Github link](https://github.com/File-New-Project/EarTrumpet)).

It's a volume mixer where the volume of each app is relative to your overall system volume, so if your speakers are set to 30% volume and a program is set to 100% volume it will play at 30%.

Together with SoundSwitch my media control is complete :)
