### ISSUE TITLE
SoundSwitch appears to crash immediately after launch

### ISSUE THREAD

**Issue by jjolly** [Belphemur/SoundSwitch#5]
Windows 10 64-bit system

SoundSwitch v3.2.0 appears to have installed correctly. When launched either from the desktop or from the start menu, a window briefly appears before closing. In the hidden icons list, the SoundSwitch icon appears until I hover the mouse pointer over it, then the icon disappears.

**Comment by kristianjgs** [comment]
Some problem.

**Comment by bessiq** [comment]
This behavior occurs for me using 3.2.1.30803. Completely removed old version and have tried reinstalling multiple times. Removed any old registry entries, files, and folders named Soundswitch as well as running CCleaner, for what it's worth.

**Comment by kristianjgs** [comment]
Yep! The problem continue

**Comment by Belphemur** [comment]
I can reproduce it on my VM but not on my main Windows x64 10.
I'm investigating the bug.

**Comment by hinac** [comment]
Hi all!

I have same problem on Windows 10 x64. The 2.4.1.4 version was installed and worked fine on Windows 7 x64 and Windows 10 x64. I have upgrade my version of Microsoft Windows (on 10 x64 version) recently and I wanted to upgrade soundswitch on 3.2.1.30803 version, the installation work fine, but he crash immediatly after start.

Thanks for your app!

**Comment by Belphemur** [comment]
I'm really sorry for this. I found the bug that's directly linked to #2. 
I'll release very soon a new version with this bug corrected.

**Comment by IT6uru** [comment]
From event viewer:
Application: SoundSwitch.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
Stack:
   at SoundSwitch.Framework.AutoStart.IsAutoStarted()
   at SoundSwitch.Forms.Settings..ctor(SoundSwitch.Main)
   at SoundSwitch.Program.Main()


.NET runtime threw the exception



Second error in event viewer:


Faulting application name: SoundSwitch.exe, version: 3.2.1.30803, time stamp: 0x55d9d376
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ffa2f5d63e7
Faulting process id: 0x2c8c
Faulting application start time: 0x01d0de618bb8ce60
Faulting application path: C:\Program Files\SoundSwitch\SoundSwitch.exe
Faulting module path: unknown
Report Id: 2324038c-90ef-440e-a8b3-afa393c55e9d
Faulting package full name: 
Faulting package-relative application ID:

**Comment by jjolly** [comment]
After completely uninstalling, successful install and execution. Works great! Thanks for your quick response.
