### ISSUE TITLE
Feature: More configurable Update Settings

### ISSUE THREAD

**Issue by TonyGravagno** [Belphemur/SoundSwitch#528]
Preface - I wrote this request and then decided I can work around it. I'm leaving it here because others might be interested. I'm following this with my resolution.

There is no complaint from me that this software is frequently updated, and aggressively and enthusiastically maintained. This software has a tray/UI component that notifies us of updates. Frequent updates means frequent notifications. I love this software but it's kinda in my face more often than I'd like.

This proposal is to add one or two options related to how frequently we want to receive updates. Either or both of these can be accepted/rejected individually or together.

1. An option to only open update notifications starting one month after the last update.
1. An option to only notify on minor updates, not point/patch-releases. Example: 5.7, 5.8, not 5.6.1, 5.6.2, 5.6.3... This requires decisions about what is and is not important enough to bump the minor version. The version might be bumped for no other reason than to get everyone to update, because a large number of patches have been applied.

Thinking more about Settings>Update Settings, I have been using the Notify Me option. I have asked for this software to get in my face. Again, no complaints here - don't misinterpret this. I chose this because to me it's better than the extremes of No notification or auto-update. I just switched to auto-update. I trust @Belphemur and I'm fine with updates to this software, as long as I don't then get nagged that I need to restart my system after an update. Will the auto-update demand attention like the notifications? We'll see. I'm still not sure I really want every update though. Personally for this software I just need critical fixes and X.Y minor updates, not every change made as it happens - again, as much as I appreciate them.

So I'm posting this here as an indication of a potential problem that I've perceived, with a potential resolution that might be adequate. I'm leaving this here in case anyone else feels some pain and feels like the existing options are not adequate for them.

I request that this ticket remain open for discussion rather than being processed immediately. Thanks!

**Comment by Belphemur** [comment]
Hello,

I understand your complaint. It's hard to see how to go about this since I'm not really regular in the release cycle ; I work on SoundSwitch in burst (usually weekend) and then months where I'm not touching the project.

Historically, SoundSwitch had the "auto-update" as default, but it felt in the current climate to be a bad idea, and it was decided to let the user choose how to interact with this. Moreover, Windows Smartscreen became more aggressive against "unknown publisher/application" which didn't help. The user was getting a big warning coming out of nowhere because SoundSwitch wanted to update. 

But yes, it's hard to find the right balance between fixing things fast and not being always in the face of the user.

I do like the idea of a double system where build (major.minor.**build**) would auto-update and the other version bump would require user interaction.

**Comment by TonyGravagno** [comment]
I don't have anything new to offer at this time, except thanks for your consideration and for leaving this open.

As time permits (ROFLMAO) let's look at other projects to see how they handle this, and what has been done to avoid the pitfalls noted here.

Best to ya.

**Comment by nmatt** [comment]
Hi, I'd like bump this issue. Updates are at times so frequent as to be annoying. Neither do I want to turn on auto-updates, for fear that one update may break things or change behavior at a time when I don't have the time to deal with it. A simple setting to only notify e.g. once every _n_ days would be very appreciated. Or maybe there is a way to manually check for updates with a command-line invocation? Then I could configure a scheduled task to check for updates.

**Comment by Belphemur** [comment]
I've implemented a "remind me later" feature that will come in the next version:

https://github.com/Belphemur/SoundSwitch/discussions/651
