### ISSUE TITLE
SoundSwitch crash when disabling all Playback devices in the Control Panel

### ISSUE THREAD

**Issue by ilendemli** [Belphemur/SoundSwitch#57]
You may have found and fixed a different bug then that i have actually issued, but here is a better explanation of the issue: Right click on the speaker icon in your taskbar, select Playback devices, disable all devices except one, run SS and select that device, now in the playback device list, deactivate that last device, see SS crash. hope you can reproduce and fix it

**Comment by Belphemur** [comment]
Thanks for the bug report and the step to reproduce.

I've been able to find where is the bug. When you disable all the devices from the Sound Playback Panel, Windows sent me a null pointer telling me the new default device doesn't exists. I didn't take this case into account.

Will be fixed in next version.

**Comment by ilendemli** [comment]
@Belphemur thanks for looking into it, it not only happens when there is just one device left, but also when a device is connected, and activated, and suddenly for example looses connection (basically gets removed/disabled), the fix you are going to implement may fix it, but i am going to report if not. have a nice NYE!
