### ISSUE TITLE
Installation/Security Issue

### ISSUE THREAD

**Issue by robburrow** [Belphemur/SoundSwitch#6]
Thanks for the update but unfortunately neither MS Smartscreen or Norton Internet Security will let me install it. Any suggestions?

**Comment by Belphemur** [comment]
I can sign the installer and the application.
The problem is, you'll have to install a certificate first before launching the installer. This certificate will be added into the trust list of Windows and then it will recognize the program and installer as trusted.

**Comment by robburrow** [comment]
Ok great, so how do I go about installing a certificate?

Thanks for your help.

Rob

--- Original Message ---

**Comment by Belphemur** [comment]
First download this: https://www.aaflalo.me/certs/AaflaloMeCertificates.zip and launcht the InstallCA.bat.
It will install my certificate into your system. Windows will then be able to recognize the installer and application.

Now download the last release of SoundSwitch 3.2.1 that is signed with that certificate.

**Comment by robburrow** [comment]
Hello again,
 
I think I managed to install the certificate ok, but now after I uninstalled the old version of Soundswitch and restart my computer I get a window asking me if I want to install this application. I click on install and just reinstalls the previous version. So I tried to run the installer for the new version again, and I just get the security warnings again??
 
Please help 
 
Date: Sun, 23 Aug 2015 07:12:45 -0700

**Comment by Belphemur** [comment]
Okay in order you'll do this:

0.  If my version is installed,  uninstall it. 
0.  Launch the previous version of SoundSwitch 
0.  Uncheck run at startup 
0.  Exit the application and uninstall it
0.  In the zip I gave you run as administrator the InstallCA.bat
0.  Input à key to launch the installation 
0.  Run the installer of the last version of SoundSwitch

On 25 August 2015 00:39:24 EEST, robburrow <notifications@github.com> wrote:
>Hello again,
> 
>I think I managed to install the certificate ok, but now after I
>uninstalled the old version of Soundswitch and restart my computer I
>get a window asking me if I want to install this application. I click
>on install and just reinstalls the previous version. So I tried to run
>the installer for the new version again, and I just get the security
>warnings again??
> 
>Please help 
> 
>Date: Sun, 23 Aug 2015 07:12:45 -0700
>From: notifications@github.com
>To: SoundSwitch@noreply.github.com
>CC: robburrow@live.co.uk
>Subject: Re: [SoundSwitch] Installation/Security Issue (#6)
>
>First download this:
>https://www.aaflalo.me/certs/AaflaloMeCertificates.zip and launcht the
>InstallCA.bat.
>
>It will install my certificate into your system. Windows will then be
>able to recognize the installer and application.
>
>
>Now download the last release of SoundSwitch 3.2.1 that is signed with
>that certificate.
>
>
>—
>Reply to this email directly or view it on GitHub.
>
>
>  
>  
>
>
> 		 	   		  
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Belphemur/SoundSwitch/issues/6#issuecomment-134388372

-- 
Best Regards, 
Antoine Aflalo

**Comment by robburrow** [comment]
I did all the things you said but I still get error messages.
![2015-08-25 13 25 46](https://cloud.githubusercontent.com/assets/13921973/9505601/4a083988-4c3b-11e5-9ea6-0dabf7b83fc0.jpg)

**Comment by Belphemur** [comment]
Please disable Norton, it's a clear false positive (like most of the time with this shitty anti-virus).

I used VirusTotal to scan the file: https://www.virustotal.com/fr/file/18a0a18f17b84971c502ffc1edbc1ac9c37c197db1f701a1afc76e6a18bc50dc/analysis/1440659137/

As you can see there is no virus or other malware in the installer, then really disable Norton it's doing more bad than good.

**Comment by robburrow** [comment]
That did the trick. I just disabled Norton whilst I installed Soundswitch and I had no problems. One of my favourite apps in now working properly again.

Thank you so much :+1:

**Comment by NelsonMinar** [comment]
Is there a way you can have your certificate signed by a trusted authority so it is installed and trusted automatically and doesn't require manual installation? I imagine it will cost money and require you verify your identity to some certificate provider. If the money is the sticking point, I'd be willing to make a one time donation.

**Comment by FireEmerald** [comment]
Normally such certificates coast **X € per year** - so it isn't done with a one time payment... but that's only what i know and found so far. Perhaps there is still somewhere a provider which offers free certificates but in the mentioned thread kind of all cost now.

[Code signing certificate for open-source projects](http://stackoverflow.com/questions/1177552/code-signing-certificate-for-open-source-projects)

**Comment by Belphemur** [comment]
@NelsonMinar I'm still toying with the idea. The biggest issue would be to remember to keep the cert up to date (pay the 85 USD per year) and that old version of SoundSwitch could have issue updating since I make the program check for my certificate to be sure it's downloading a trusted installer.

The cheapest/easier provider I found is: http://codesigning.ksoftware.net/

**Comment by NelsonMinar** [comment]
Thanks for your answer and thoughtful research. I was motivated to write because the current user experience for SoundSwitch updates is pretty bad. I just randomly see a UAC popup (interrupting whatever I'm doing) with a request to approve an anonymous "installer.exe". You have to click through to "Details" to even see it's SoundSwitch. For now I've just disabled background updates, which actually is a fine enough solution, but a signed cert would be better.

I'm sorry I don't know anything about the Windows ecosystem and how signed binaries work, it's a shame Microsoft doesn't have a good solution. When I wrote my note I had in mind a one-time $100 donation, thinking maybe that'd fix the problem. I can understand your hesitance to get committed to ongoing expenses for a free software project.

**Comment by Belphemur** [comment]
@NelsonMinar, Well you'd still have the popup even with a trusted Microsoft certificate installed. 

Anytime you launch an installer, Windows does that, the only change is you'd see the "Publisher: SoundSwitch".

In the newer version of the installer, the user has the choice to install my certificate to make your Windows recognize SoundSwitch as a trusted publisher. It's selected by default WHEN installed manually. When the auto-update does the install, the certificate doesn't get installed.

You could download the last version, install it manually and check the box about trusting the certificates. But as I said, you'll still get the UAC warning, just with "Publisher: SoundSwitch".

Because of all those annoyance, with @FireEmerald we decided that the default "Update action" is notify, letting the user go through the installer and removing the "surprise" linked with the UAC popup of Windows.
