### ISSUE TITLE
Settings lost on Windows login

### ISSUE THREAD

**Issue by drkvogel** [Belphemur/SoundSwitch#622]
**Describe the bug**
In Settings, Playback I usually have two devices for my HP Elitebook 840 G3, speakers and headphones (when they are plugged in), and I usually have them both checked as playback devices for SoundSwitch.

Whenever Windows reboots (i.e. often), SoundSwitch appears not to work, until I go to the settings and notice both devices have become unchecked again.

**Version**
SoundSwitch v5.9.0.19580

**To Reproduce**
1. Enable playback devices for SoundSwitch
2. Reboot
3. No playback devices are enabled

**Expected behavior**
SoundSwitch should remember the preferences - the devices previously enabled should remain enabled.

**Comment by Belphemur** [comment]
Hello,

It's possible your configuration got corrupted.

Can you attach the content of %appdata%/SoundSwitch to this issue as a zip file ?

Then can you stop SoundSwitch then delete the folder %appdata%/SoundSwitch and lastly restart SoundSwitch and reconfigure it ?


Sent from Nine
________________________________
From: Chris Bird ***@***.***>
Sent: Sunday, May 2, 2021 14:02
To: Belphemur/SoundSwitch
Cc: Subscribed
Subject: [Belphemur/SoundSwitch] Settings lost on Windows login (#622)

Describe the bug
In Settings, Playback I usually have two devices for my HP Elitebook 840 G3, speakers and headphones (when they are plugged in), and I usually have them both checked as playback devices for SoundSwitch.
Whenever Windows reboots (i.e. often), SoundSwitch appears not to work, until I go to the settings and notice both devices have become unchecked again.
Version
SoundSwitch vX.X.X
To Reproduce
Steps to reproduce the behavior:
Enable playback devices for SoundSwitch
Reboot
No playback devices are enabled
Expected behavior
SoundSwitch should remember the preferences - the devices previously enabled should remain enabled.

**Comment by drkvogel** [comment]
Sure, zip attached: [AppData-SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/6415366/AppData-SoundSwitch.zip)
