### ISSUE TITLE
series of popups every restart

### ISSUE THREAD

**Issue by Oscillator1** [Belphemur/SoundSwitch#68]
When the windows come up with soundswitch, it displayes a series of like 10 popups every time.
it didn't happen before with the same hardware.

**Comment by Belphemur** [comment]
Can you screenshot the popup ?

What are their content exactly, which version of Windows are you using ?

**Comment by Oscillator1** [comment]
I use Windows 10 64bit
the actual bug is that it switches between the devices multiple times at startup.
It's showing the windows notifications according to settings.
It happens only in the newer versions (3.8 and up, even 3.9.2), I've downloaded V3.6.5 and it works fine.

**Comment by Belphemur** [comment]
The problem lies with your Windows. SoundSwitch is using the Windows APIs to be notified in case of change of default audio device.

If you see multiple notification at startup it means simply your OS is switching between the default audio device back and forth by itself.

On 5 February 2016 21:38:06 GMT-05:00, Maor Druker <notifications@github.com> wrote:
>I use Windows 10 64bit
>the actual bug is that it switches between the devices multiple times
>at startup.
>It's showing the windows notifications according to settings.
>It happens only in the newer versions (3.8 and up, even 3.9.2), I've
>downloaded V3.6.5 and it works fine.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Belphemur/SoundSwitch/issues/68#issuecomment-180661178

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Oscillator1** [comment]
so why does it happen only at the newer versions?
i'll just keep v3.6.5 then...

**Comment by Belphemur** [comment]
Because in the older version I was giving notification only when 
SoundSwitch is switching itself the device.

What you can do, is simply disable them.
