### ISSUE TITLE
Switching already running applications

### ISSUE THREAD

**Issue by yar229** [Belphemur/SoundSwitch#70]
On Windows 7 sound from already running Chrome browser was switching immediately, but on Windows 10 I need to restart it.
Is it possibly to make immediately switching on windows 10?

Thanks.

Btw, 3d games needs to be restarted both on Windows 7 and 10

**Comment by Belphemur** [comment]
Hello @yar229 

Are you using the beta version or the stable version?
If it's the stable version, can you try the beta?

Do you have the latest version of Windows 10 ? (CTRL+X -> Cmd as admin -> winver )
![image](https://cloud.githubusercontent.com/assets/197810/13198031/f23e38fc-d7cb-11e5-961c-c0caa3825b86.png)

If not I advise you to reenable the auto-update of windows since it's an issue that should have been corrected in one of the update package.

**Comment by yar229** [comment]
Google Chrome 48.0.2564.116

![image](https://cloud.githubusercontent.com/assets/5150160/13219311/404d0e64-d980-11e5-8501-f51dd4fc6aff.png)

Windows is insider preview version in fast ring.

I don't remember Windows 10 build I've installed instead of Windows 7, but since that time windows and chrome has been updated several times and nothing changed.

**Comment by xXLike** [comment]
Hello, i got the same problem with mozilla especially with deezer.(working on youtube)
I saw on Deezer,Mozilla use the "plugin container" and still to the first device when i try to switch an another device in soundswitch.
Latest W10 1511 also.

**Comment by yar229** [comment]
... everything Ok on another windows 10 version

![image](https://cloud.githubusercontent.com/assets/5150160/13220620/2f013a42-d988-11e5-8ff4-9e6b6ec23ac6.png)

**Comment by Belphemur** [comment]
Are you both using the latest beta? minimum 3.9.2?

You could also try to change the default device manually in the control panel while the music/sound is playing and see if it does the switch. If it doesn't, it's clearly a problem with Windows or the application.

This issue has been reported multiple time and only on Windows 10.

**Comment by FireEmerald** [comment]
Some applications and most games ignore it if you switch the default sound output device, while the application is running - that's normal. Got here several examples on Win7 system.

I would try it as explained by Belhemur to change it manually if the result differs.

**Comment by lotscharsjackl** [comment]
I got the same behavior on Win 10 Version 1511 (Build 10586.164) when trying to switch audio while watching a video in Flash Player / Firefox. The same thing used to work when i was still on Win7.

Switching the default audio device in the control panel has no effect for me, so this could just behave differently in Windows 10.

**Comment by FireEmerald** [comment]
Switched to Windows 10 a few days ago.

- Windows 10 Pro 64-bit
Version 1511 (Build 10586.164)

- Google Chrome
Version 49.0.2623.110 m

- Adobe Flash Player
21,0,0,197 installed

- SoundSwitch
Version 3.9.6.13790

Switching the playback device while running for example:
- Spotify or Youtube

works as intended and the playback continues on the new device.

**Comment by yar229** [comment]
With a new windows build arrived everything is ok

**Comment by FireEmerald** [comment]
Ok, since some days now i noticed the same problem. If i switch the playback device while using Spotify (Flash) on Firefox, the output won't switch to the new device.

The problem seems like to come from Flash, because if i open two tabs one based on Flash (Spotify) and another one on HTML5 (YouTube) the YouTube playback switches, but not Spotify.

Microsoft Windows 10 Pro
10.0.10586 Build 10586

Firefox Portable 46.0.1 with Flash 21.0.0.242

**Comment by Belphemur** [comment]
@FireEmerald can you try the same with Chrome ?

I think it's linked to the way firefox deal with flash (with their plugincontainer executable).

Also, if when you switch manually in the control panel, the sound doesn't switch, I won't be able to do much.

**Comment by FireEmerald** [comment]
I think it's only a firefox related problem - but i'm not 100% sure, because i couldn't find a "test video" which requires the flash player. Spotify is running with HTML5 under chrome as well as youtube...
