### ISSUE TITLE
Intermittent - app closes when switching devices.

### ISSUE THREAD

**Issue by mikefirefly** [Belphemur/SoundSwitch#715]
**Describe the bug**
Sometimes the app just closes when switching devices.

**Version**
SoundSwitch v5.10.0.19681 on Win10.

**To Reproduce**
1. Switch the device using hotkey

**Expected behavior**
Device switched.

**Actual behavior**
Device not switched and program closes.

**Screenshots**
N/A

**Additional context**
This is intermittent. Any way I can get debug logs?

**Comment by Belphemur** [comment]
Hello,

Can you try with v5.11.2 ?

I unfortunately broke the updater in 5.10.

Sent from Nine

________________________________
From: mikefirefly ***@***.***>
Sent: Sunday, August 8, 2021 08:11
To: Belphemur/SoundSwitch
Cc: Subscribed
Subject: [Belphemur/SoundSwitch] Intermittent - app closes when switching devices. (#715)

Describe the bug
Sometimes the app just closes when switching devices.
Version
SoundSwitch v5.10.0.19681 on Win10.
To Reproduce
Steps to reproduce the behavior:
Switch the device using hotkey
Expected behavior
Device switched.
Actual behavior
Device not switched and program closes.
Screenshots
N/A
Additional context
This is intermittent. Any way I can get debug logs?
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mikefirefly** [comment]
Thanks for the heads up, I had no idea that there was an update. Installing now and will report what happens.
FWIW, my devices do NOT have the same name: https://i.imgur.com/sj3AtVh.png

**Comment by mikefirefly** [comment]
Just had a crash like in the previous version.
