### ISSUE TITLE
Per-application switch

### ISSUE THREAD

**Issue by Fiip** [Belphemur/SoundSwitch#77]
Hi, SoundSwitch works great for me, but it seems to switch all active applications at once - is there a per-application switch function? The applications that get switched are flash in the browser and a fullscreen game.

**Comment by Belphemur** [comment]
I would love to implements, but there is no way to do it cleanly with the Windows API. To be honest, what SoundSwitch do, is already using an undocumented API that shouldn't be used.

A program can choose on which sound card it output its sound. Most of the program (like games, browsers, etc ...) ask Windows for the default audio output and ask the OS to be notified if the device change.

To implement what you ask, I would need to find a way to trigger that notification only for the wanted application, this is not possible and would in fact be giving to much control on outside application to the currently running application.

**Comment by SolarLune** [comment]
Yo! I'm a user of this application and have been following its progress here on Github for awhile. Just wanted to pipe in and say that I believe it is possible to reassign programs to sound devices, as I know of one program that does it already. Is it just that the API to do it is too finicky and awkward to get to work?

Anyway, thanks for the application - it's pretty useful as it is!

**Comment by Belphemur** [comment]
The other applications are implementing their workaround since there is no(documented) API available. A lot of them base their feature on the idea that the app "switched" doesn't implement correctly the notifier for the change of default device.
Best examples are games, they only check for the audio device at launch and then stop checking. But most desktop apps are listening the change of default device like chrome, firefox, etc ... which mean, you need to trick it into believing either the default device didn't change, or it changed to the wanted device... and that without making all other app switch.

**Comment by SolarLune** [comment]
Ah, I see. Just wanted to let you know that it was possible; wasn't sure of the specifics, themselves. Thanks for the info!
