### ISSUE TITLE
[FEATURE REQUEST] Reorder available devices

### ISSUE THREAD

**Issue by hachesilva** [Belphemur/SoundSwitch#771]
It would be a good idea to have an option to reorder available devices in the list of selected devices. This is useful when you have several devices of the same type (speakers, headphones) but they are in a random order:
Speaker1
Headphones1
Speaker2
Headphones2

Expected order:
Speaker1
Speaker2
Headphones1
Headphones2

**Comment by Belphemur** [comment]
Hello,

They are ordered by the order you selected them.

Sent from Nine
________________________________
From: Hernán Silva ***@***.***>
Sent: Saturday, September 25, 2021 13:33
To: Belphemur/SoundSwitch
Cc: Subscribed
Subject: [Belphemur/SoundSwitch] [FEATURE REQUEST] Reorder available devices (#771)

It would be a good idea to have an option to reorder available devices in the list of selected devices. This is useful when you have several devices of the same type (speakers, headphones) but they are in a random order:
Speaker1
Headphones1
Speaker2
Headphones2
Expected order:
Speaker1
Speaker2
Headphones1
Headphones2
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
