### ISSUE TITLE
SoundSwitch Crashing after PC is Sleeping

### ISSUE THREAD

**Issue by Belphemur** [Belphemur/SoundSwitch#797]
### Discussed in https://github.com/Belphemur/SoundSwitch/discussions/796

<div type='discussions-op-text'>

<sup>Originally posted by **Blake-V-Walker** October 17, 2021</sup>
Hi All - Whenever I come back to my PC after having it slept for a while, my SoundSwitch has crashed without fail.

Is anyone else having this issue? 

Clicking "Yes" to share the error with the developers just takes me to the main Github page. 

I have reinstalled with the same issues. 

![image](https://user-images.githubusercontent.com/73499422/137659628-6fe47986-ae52-457c-bedb-fbcb6220c8bd.png)
</div>

**Comment by jymorvan** [comment]
When the PC wakes up, sometimes I just have a warning sound but I don't see anything else, and sometimes I have the popup from the original post ("It seems SoundSwitch has crashed ..." ), I click "ok", and the popup reappears another time, again I click ok, and that's it, I must then restart SoundSwitch.
But I confirm that it is every time the PC wakes from sleep mode, never otherwise and that it appeared with the latest version of SoundSwitch.
(sorry for my english)

**Comment by Blake-V-Walker** [comment]
I'll give this version a go for a day or so and get back to you.
