### ISSUE TITLE
Unticked Playback Choice Returns after Monitor Wakes Up.

### ISSUE THREAD

**Issue by marc0523** [Belphemur/SoundSwitch#975]
**Describe the bug**
Step 1: Untick "DELL U2913WM (NVIDIA High Definition Audio)" from the available Playback options, leaving only my headphones and motherboard speakers.
Step 2: Leave the PC alone long enough for the monitor to go into standby mode (powered off, but PC itself does not go into sleep mode)
Step 3: Wake up PC by moving mouse, pressing key on keyboard etc.
Step 4: "DELL U2913WM (NVIDIA High Definition Audio)" has been re-ticked and is listed on the Selected area of the Playback options.
Step 5: Untick, and the issue will go away until the monitor next goes to sleep.

Please note: this is a new problem, I _believe_ it is only since the last update, but unsure.

**Version**
SoundSwitch v6.4.0.0

**To Reproduce**
See above.

**Expected behavior**
Chosen options should stick.

**Screenshots**
![2022-08-03](https://user-images.githubusercontent.com/110537282/182595258-562e1bc1-128e-4842-87f2-4d8bd4914acf.png)

**Additional context**
Nvidia driver: 516.59 Release 06/28/2022
Windows 10 21H2 (OS Build 19044.1826)

**Comment by Belphemur** [comment]
Hello,

I had an issue with the auto add feature in v6.4.0.
Can you try with the latest version v6.4.1 ?

Sent from Nine
________________________________
From: marc0523 ***@***.***>
Sent: Wednesday, August 3, 2022 07:22
To: Belphemur/SoundSwitch
Cc: Subscribed
Subject: [Belphemur/SoundSwitch] Unticked Playback Choice Returns after Monitor Wakes Up. (Issue #975)

Describe the bug
Step 1: Untick "DELL U2913WM (NVIDIA High Definition Audio)" from the available Playback options, leaving only my headphones and motherboard speakers.
Step 2: Leave the PC alone long enough for the monitor to go into standby mode (powered off, but PC itself does not go into sleep mode)
Step 3: Wake up PC by moving mouse, pressing key on keyboard etc.
Step 4: "DELL U2913WM (NVIDIA High Definition Audio)" has been re-ticked and is listed on the Selected area of the Playback options.
Step 5: Untick, and the issue will go away until the monitor next goes to sleep.
Please note: this is a new problem, I believe it is only since the last update, but unsure.
Version
SoundSwitch v6.4.0.0
To Reproduce
See above.
Expected behavior
Chosen options should stick.
Screenshots
If applicable, add screenshots to help explain your problem.
Additional context
Nvidia driver: 516.59 Release 06/28/2022
Windows 10 21H2 (OS Build 19044.1826)

**Comment by marc0523** [comment]
Yes, looks like it's fixed in the latest version, thanks!
